# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of- name: tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Listing
        run: |
          ls ${{github.workspace}}
          
      - name: Second
        run: |
          ls ${{github.workspace}}/Source/pim/Source/DemoApp/app/build/outputs/apk/
     
      - name: App centre deploy
        uses: wzieba/AppCenter-Github-Action@v1.3.1
        with:
          appName: Github-Actions/Testing
          token: 5d4aea88ca266ed830315cf4166927889a12875b
          # Distribution group
          group: test
          # Artefact to upload (.apk or .ipa)
          file: /Source/pim/Source/DemoApp/app/build/outputs/apk/release/pimApp-release.apk
          # Release notes visible on release page
          releaseNotes: R-1
          # If true, send an email notification to the distribution group
          notifyTesters: true
          
     
